Test/KLBP-284: Document typeid incorrect.
beprems/KYB-lbp-front pull request #148
Opened 2021-06-07 13:59 UTC by iuliudascalu

2021-06-07 14:02 UTC, ioan-iacob-netea requested changes

2021-06-07 14:02 UTC, ioan-iacob-netea commented on src/components/step2/Step2Content.tsx
> +    journeyStatus,
Please sort properties.

2021-06-07 14:02 UTC, ioan-iacob-netea commented on src/hooks/useStep2Hook.ts
> +      identity_document_type:
Please use camel case for the name like the rest of the properties.

2021-06-07 14:02 UTC, ioan-iacob-netea commented on src/services/API/person.ts
> +    identity_document_type,
Please sort the properties.

2021-06-07 14:37 UTC, andreir-suciu commented on src/hooks/useStep2Hook.ts
> +      identity_document_type:
I think we should keep this name as it is on LBP and on BE side.

2021-06-07 14:38 UTC, andreir-suciu approved these changes

2021-06-07 14:47 UTC, ioan-iacob-netea commented on src/hooks/useStep2Hook.ts
> +      identity_document_type:
Having multiple naming strategies is confusing. If we are talking about parameters being sent in API calls they can be adjusted by transformations if there is a concrete request for them to be in a certain way.

2021-06-07 15:15 UTC, iuliudascalu commented on src/components/step2/Step2Content.tsx
> +    journeyStatus,
Done.

2021-06-07 15:16 UTC, iuliudascalu commented on src/services/API/person.ts
> +    identity_document_type,
Done.

2021-06-07 15:16 UTC, iuliudascalu commented on src/hooks/useStep2Hook.ts
> +      identity_document_type:
Done.

2021-06-08 05:58 UTC, ioan-iacob-netea approved these changes

2021-06-08 06:01 UTC, merged