KLBP-306: Update step 2 EI create and edit person.
beprems/KYB-lbp-front pull request #158
Opened 2021-06-14 14:51 UTC by andreir-suciu

2021-06-14 15:46 UTC, mariuspop86 commented on src/components/Journeys/IndividualCompany/Step2/Step2Content.tsx
> +  const { journeyStatus, onClickNext, onClickPrevious, isPersonValid } =
If there are more then 3 items you should set them one below the other

2021-06-14 15:47 UTC, mariuspop86 commented on src/services/utils.ts
> +export const checkIfStringsAreEmpty = (inputs: string[]) => {
```suggestion
export const checkIfStringsAreEmpty = (inputs: string[]) => {
export const checkIfStringsAreEmpty = (strings: string[]) => {
```
You are checking strings right?

2021-06-14 15:49 UTC, mariuspop86 commented on src/services/utils.ts
> +  inputs.forEach((input: string) => {
Instead of forEach you could use [some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some), or [every](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every)

2021-06-14 15:52 UTC, mariuspop86 commented on src/hooks/useStep2Hook.ts
> +
Why do we make a new request here? This should be moved where you call `deletePersonData()`
This function should just delete the person data and that is it

2021-06-14 15:53 UTC, mariuspop86 commented on src/components/Journeys/IndividualCompany/Step2/PersonInfoCard.tsx
> +                status === 'invalid' || !status ? 'invalid.viewMode' : status
I think we should move this logic outside of JSX.

2021-06-14 15:56 UTC, andreir-suciu commented on src/components/Journeys/IndividualCompany/Step2/Step2Content.tsx
> +  const { journeyStatus, onClickNext, onClickPrevious, isPersonValid } =
It is formatted automatically by prettier on save.

2021-06-14 17:42 UTC, andreir-suciu commented on src/services/utils.ts
> +export const checkIfStringsAreEmpty = (inputs: string[]) => {
Updated param name to strings

2021-06-14 17:42 UTC, andreir-suciu commented on src/services/utils.ts
> +  inputs.forEach((input: string) => {
Done

2021-06-14 17:42 UTC, andreir-suciu commented on src/hooks/useStep2Hook.ts
> +
Done

2021-06-14 17:42 UTC, andreir-suciu commented on src/components/Journeys/IndividualCompany/Step2/PersonInfoCard.tsx
> +                status === 'invalid' || !status ? 'invalid.viewMode' : status
Done

2021-06-15 06:31 UTC, ioan-iacob-netea requested changes

2021-06-15 06:31 UTC, ioan-iacob-netea commented on src/hooks/useStep2Hook.ts
> +    if (person && !isPersonValid && mode === 'create') {
Please create a constant for 'create'.

2021-06-15 06:31 UTC, ioan-iacob-netea commented on src/interfaces/Step2.ts
> +  getPersonData: () => void
Please sort properties.

2021-06-15 06:31 UTC, ioan-iacob-netea commented on src/services/utils.ts
> +  return strings.some((string: string) => !string || string === '')
Maybe the modal can clean this method a bit?
`return (!strings) ? true : strings.some((string: string) => !string || string === '')`

2021-06-15 07:03 UTC, iuliudascalu commented on src/hooks/useStep2ViewModeHook.ts
> +          if (!status || status === 'invalid') {
Please add a constant for invalid.

2021-06-15 07:59 UTC, andreir-suciu commented on src/hooks/useStep2Hook.ts
> +    if (person && !isPersonValid && mode === 'create') {
Done

2021-06-15 07:59 UTC, andreir-suciu commented on src/interfaces/Step2.ts
> +  getPersonData: () => void
Done

2021-06-15 08:00 UTC, andreir-suciu commented on src/services/utils.ts
> +  return strings.some((string: string) => !string || string === '')
Done

2021-06-15 08:00 UTC, andreir-suciu commented on src/hooks/useStep2ViewModeHook.ts
> +          if (!status || status === 'invalid') {
Done

2021-06-15 08:08 UTC, iuliudascalu approved these changes

2021-06-15 08:19 UTC, ioan-iacob-netea requested changes

2021-06-15 08:19 UTC, ioan-iacob-netea commented on src/hooks/useStep2Hook.ts
> +    isPersonValid,
Please sort properties.

2021-06-15 08:22 UTC, mariuspop86 commented on src/services/utils.ts
> +  !strings ? true : strings.some((string: string) => !string || string === '')
`!string || string === ''` => `!string`
I think this check is enought

2021-06-15 08:29 UTC, andreir-suciu commented on src/services/utils.ts
> +  !strings ? true : strings.some((string: string) => !string || string === '')
This would be ok if there would be only one string but it is an array of strings as parameter.

2021-06-15 08:34 UTC, andreir-suciu commented on src/hooks/useStep2Hook.ts
> +    isPersonValid,
Done

2021-06-15 09:55 UTC, ioan-iacob-netea approved these changes

2021-06-15 18:55 UTC, mariapitechplus commented on src/hooks/useStep2Hook.ts
> +    }
I'm not sure I understand this block of code. isPersonValid is determined when getting the person from the BE. So if we have received some data from the BE but some fields are empty, and we click "Enregistrer button we delete the person? Why? I think we should reset the form as the task says but not to delete the person. Instead, we should update the existing one with new values added by the user. What do you think @mariuspop86 ?

2021-06-16 06:51 UTC, mariuspop86 approved these changes

2021-06-16 06:59 UTC, mariuspop86 commented on src/hooks/useStep2Hook.ts
> +    }
One acceptance criteria is that if the person info is missing then the user must fill in all the data, that is why we delete the person and later in the code we create a new one. It would of been easier to update, but we don't have an update API at the moment so we went for this workaround.

2021-06-16 07:11 UTC, merged