KC-164: Societe de droit prive step1.
beprems/KYB-lbp-front pull request #161
Opened 2021-06-15 09:54 UTC by iuliudascalu

2021-06-15 10:20 UTC, ioan-iacob-netea requested changes

2021-06-15 10:20 UTC, ioan-iacob-netea commented on src/enums/common.ts
> +export const MONTANT_LIMIT = 200000
Please use an English variable name, ex AMOUNT_LIMIT.

2021-06-15 10:20 UTC, ioan-iacob-netea commented on src/interfaces/Upload.ts
> +  isOptional?: boolean
Please sort the properties.

2021-06-15 10:20 UTC, ioan-iacob-netea commented on src/lang/fr.json
> +  "step1.private.company.title1": "Dernière copie complète des statuts de la société *",
Please sort the translations.

2021-06-15 10:20 UTC, ioan-iacob-netea commented on src/components/Journeys/Common/Step1InfoText.tsx
> +      default:
The default text is set to be the one for Individual Company? If we can get to display this component without client typology maybe have an empty tag on the default render should be better.

2021-06-15 10:20 UTC, ioan-iacob-netea commented on src/hooks/useStep1FormHook.ts
> +    : documentsInitialState
If documentsInitialState refers to individual company initial state we should rename the parameter to better reflect what it refers to. Also, for the next company type are we going to add another modal or should we switch to a switch (pun not intended)?

2021-06-15 13:34 UTC, iuliudascalu commented on src/enums/common.ts
> +export const MONTANT_LIMIT = 200000
Done. (I've removed the constant as it was no longer needed)

2021-06-15 13:35 UTC, iuliudascalu commented on src/lang/fr.json
> +  "step1.private.company.title1": "Dernière copie complète des statuts de la société *",
Done.

2021-06-15 13:35 UTC, iuliudascalu commented on src/components/Journeys/Common/Step1InfoText.tsx
> +      default:
Done.

2021-06-15 13:40 UTC, iuliudascalu commented on src/interfaces/Upload.ts
> +  isOptional?: boolean
Done.

2021-06-15 13:41 UTC, iuliudascalu commented on src/hooks/useStep1FormHook.ts
> +    : documentsInitialState
Done. ( I changed it with an switch)

2021-06-15 15:39 UTC, ioan-iacob-netea requested changes

2021-06-15 15:39 UTC, ioan-iacob-netea commented on src/components/Journeys/PrivateCompany/Step1/Step1UploadTooltips/Step1TooltipContent.tsx
> +        <>
Please separate the returned blocks of code as separate components for a cleaner code.

2021-06-15 15:39 UTC, ioan-iacob-netea commented on src/hooks/useStep1FormHook.ts
> +  getStep1DocumentsInitialStateByJourneyType,
:+1:

2021-06-16 06:13 UTC, mariuspop86 commented on src/components/Journeys/Common/Step1InfoText.tsx
> +      case INDIVIDUAL_COMPANY:
This is what we want to avoid with the refactoring, conditions inside the code. Please create two separate files for each journey

2021-06-16 06:21 UTC, mariuspop86 commented on src/enums/common.ts
> -export const YES_VALUE = '1'
Please don't move around code, this will just create confusion and conflicts

2021-06-16 06:25 UTC, iuliudascalu commented on src/enums/common.ts
> -export const YES_VALUE = '1'
This is why i moved, because is different on recette and dev and we will get this conflict every time. (because now it should be the same)

2021-06-16 13:05 UTC, iuliudascalu commented on src/components/Journeys/PrivateCompany/Step1/Step1UploadTooltips/Step1TooltipContent.tsx
> +        <>
Done.

2021-06-16 13:05 UTC, iuliudascalu commented on src/components/Journeys/Common/Step1InfoText.tsx
> +      case INDIVIDUAL_COMPANY:
Done.

2021-06-23 12:22 UTC, mariuspop86 commented on src/components/Journeys/PrivateCompany/Step1/UploadFiles.tsx
> +      {state.map((item: IFileState, index: number) => {
```suggestion
      {state.map((fileState: IFileState, index: number) => {
```

2021-06-23 12:23 UTC, mariuspop86 commented on src/components/Journeys/PrivateCompany/Step1/UploadFiles.tsx
> +              <Upload
```suggestion
              <Upload
              {...{dispatch, fileState, index, label: Step1UploadLabel(fileState.typeId), onChange}}
```

2021-06-23 14:09 UTC, iuliudascalu commented on src/components/Journeys/PrivateCompany/Step1/UploadFiles.tsx
> +              <Upload
Done.

2021-06-23 14:09 UTC, iuliudascalu commented on src/components/Journeys/PrivateCompany/Step1/UploadFiles.tsx
> +      {state.map((item: IFileState, index: number) => {
Done.

2021-06-24 06:24 UTC, andreir-suciu approved these changes

2021-06-24 09:38 UTC, mariuspop86 approved these changes

2021-06-24 10:50 UTC, ioan-iacob-netea approved these changes

2021-06-25 11:30 UTC, merged