Klbp 197 private company step 2
beprems/KYB-lbp-front pull request #162
Opened 2021-06-15 20:10 UTC by mariapitechplus

2021-06-16 06:37 UTC, andreir-suciu commented on src/components/Journeys/PrivateCompany/LegalRepresentativeSection/LegalRepresentativeSection.tsx
> +export default LegalRepresentativeSection
This file is the same as the one for Legal representative section from Individual company. Please move one of them in Common folder and delete the other.

2021-06-16 06:39 UTC, andreir-suciu commented on src/components/Journeys/PrivateCompany/Step2/PersonInfoCard.tsx
> +export default PersonInfoCard
Same as for LegalRepresentativeSection.

2021-06-16 06:45 UTC, andreir-suciu commented on src/components/Journeys/PrivateCompany/Step2/PersonInfoSection.tsx
> +        />
I think you can move PersonInfoSection to common folder and reuse it. Also, value logic can be made there or extract the title another component.

2021-06-16 06:59 UTC, mariapitechplus commented on src/components/Journeys/PrivateCompany/LegalRepresentativeSection/LegalRepresentativeSection.tsx
> +export default LegalRepresentativeSection
Unfortunately, the interfaces are different. The response for the get person/s endpoints are different depending of the journey type. I think it was not a good idea to mix interfaces for the same component, so I chose to not add these components in common folder. What do you think about this @mariuspop86 ?

2021-06-16 07:01 UTC, mariapitechplus commented on src/components/Journeys/PrivateCompany/LegalRepresentativeSection/LegalRepresentativeSection.tsx
> +export default LegalRepresentativeSection
Maybe I can do a "wrapper" components that returns this one ? In this way I can move LegalRepresentativeSection in the common folder and use it in the wrapper. Could be an option

2021-06-16 07:56 UTC, ioan-iacob-netea requested changes

2021-06-16 07:56 UTC, ioan-iacob-netea commented on src/__tests__/pages/steps/Step2PrivateCompany.test.tsx
> +  // describe('Step 2 form', () => {
Please remove the commented code if it is not needed.

2021-06-16 07:56 UTC, ioan-iacob-netea commented on src/components/Journeys/PrivateCompany/Step2/PersonInfoSection.tsx
> +          values={{ number: index !== undefined ? index + 1 : '' }}
The number property can get an empty string as value? I think we should have a different variable name to better reflect its content. Please note that there are multiple similar instances of this used.

2021-06-16 07:56 UTC, ioan-iacob-netea commented on src/components/Journeys/PrivateCompany/Step2/Step2Content.tsx
> +                Ajouter un nouveau Représentant Légal
Please add this text as a translation.

2021-06-16 07:56 UTC, ioan-iacob-netea commented on src/components/Journeys/PrivateCompany/Step2/Step2Form.tsx
> +          representativeType="legalRepresentative"
Please add an enum for legalRepresentative as it is used in multiple places.

2021-06-16 07:56 UTC, ioan-iacob-netea commented on src/enums/step2Enums.ts
> +export const DOCUMENT_TYPE_ID = '1'
Please move the variable at the end of this group in order to have them sorted alphabetically.

2021-06-16 07:56 UTC, ioan-iacob-netea commented on src/enums/step2Enums.ts
> +export const MAX_RP = 3
What does RP stand for? Please try not to abbreviate variables and constants.

2021-06-16 07:56 UTC, ioan-iacob-netea commented on src/interfaces/LegalRepresentative.ts
> +  cancelEdit: () => void
Please sort interface properties.

2021-06-16 07:56 UTC, ioan-iacob-netea commented on src/interfaces/LegalRepresentative.ts
> +  closeCard?: () => void
Please sort interface properties.

2021-06-16 07:56 UTC, ioan-iacob-netea commented on src/interfaces/Step2.ts
> +  form: UseFormReturn<Record<string, IStep2FormData>>
Please sort interface properties.

2021-06-16 07:56 UTC, ioan-iacob-netea commented on src/interfaces/Step2.ts
> +  isEditModeOpen: boolean
Please sort interface properties.

2021-06-16 17:28 UTC, mariapitechplus commented on src/components/Journeys/PrivateCompany/Step2/PersonInfoSection.tsx
> +          values={{ number: index !== undefined ? index + 1 : '' }}
I can be 0, as the first index in an array is 0. Therefore is it is 0, means that is the first entry in the array and I want the dynamic message

2021-06-16 17:52 UTC, mariapitechplus commented on src/components/Journeys/PrivateCompany/Step2/Step2Content.tsx
> +                Ajouter un nouveau Représentant Légal
done

2021-06-16 17:52 UTC, mariapitechplus commented on src/__tests__/pages/steps/Step2PrivateCompany.test.tsx
> +  // describe('Step 2 form', () => {
done

2021-06-16 17:53 UTC, mariapitechplus commented on src/components/Journeys/PrivateCompany/Step2/Step2Form.tsx
> +          representativeType="legalRepresentative"
done

2021-06-16 17:53 UTC, mariapitechplus commented on src/enums/step2Enums.ts
> +export const DOCUMENT_TYPE_ID = '1'
done

2021-06-16 17:53 UTC, mariapitechplus commented on src/enums/step2Enums.ts
> +export const MAX_RP = 3
changed name

2021-06-16 17:55 UTC, mariapitechplus commented on src/interfaces/LegalRepresentative.ts
> +  closeCard?: () => void
sort by what?

2021-06-16 18:09 UTC, ioan-iacob-netea commented on src/components/Journeys/PrivateCompany/Step2/PersonInfoSection.tsx
> +          values={{ number: index !== undefined ? index + 1 : '' }}
Ok, but if index is undefined the default is ' ' which is not a number.

2021-06-16 18:10 UTC, ioan-iacob-netea commented on src/interfaces/LegalRepresentative.ts
> +  closeCard?: () => void
Yes, we should try to keep them sorted alphabetically. Some slip through, but it is a work in progress to have them all tidy :)

2021-06-16 18:12 UTC, ioan-iacob-netea requested changes

2021-06-16 18:12 UTC, ioan-iacob-netea commented on src/lang/fr.json
> +  "step2.button.addCard": "Ajouter un nouveau Représentant Légal",
Please also keep the translations ordered alphabetically.

2021-06-16 18:36 UTC, mariapitechplus commented on src/components/Journeys/PrivateCompany/Step2/PersonInfoSection.tsx
> +          values={{ number: index !== undefined ? index + 1 : '' }}
I think you confuse the property index, that can be a number or is undefined ( I have used the same interface for cards but different component), with the place its value is used. An index is a number and should stay like this, doesn't matter where do I use it and for what purpose. The if statement here is needed only because I have used the same interface and I cannot add + 1 to the index because the lint says that index can be undefined. Maybe we can find another way to handle it, if you have any suggestion please let me know. Thanks

2021-06-17 06:57 UTC, ioan-iacob-netea requested changes

2021-06-17 06:57 UTC, ioan-iacob-netea commented on src/interfaces/Step2.ts
> +  isDisclaimerActive: boolean
Please sort the interface properties.

2021-06-17 07:29 UTC, andreir-suciu commented on src/hooks/useStep2SecondaryPersonViewModeHook.ts
> +          const { status } = await getPersonDocument(
I think you can use the useStep2ViewModeHook here. The only diference is that you call another function to get the document status and the personId parameter. You could add an optional personId parameter there and update getDocument call
const { status } = personId ? await getPersonDocument() : await getDocumentInfo()

2021-06-18 06:16 UTC, ioan-iacob-netea approved these changes

2021-06-23 07:06 UTC, mariuspop86 commented on src/__mock__/fetchMock.ts
> +export const mockGetSecondaryPersons = (
If you update the interface to a generic, this could be transformed into a generic function.
```suggestion
export const mockRequest<T> = (response: T[]) => {
```

2021-06-23 07:53 UTC, mariuspop86 commented on src/components/Journeys/Common/Step2/PersonInfoSection.tsx
> +          values={{ number: index !== undefined ? ` nº${index + 1}` : '' }}
👍

2021-06-23 07:54 UTC, mariuspop86 commented on src/components/Journeys/IndividualCompany/Step2/Step2Content.tsx
> +  const { onClickNext, onClickPrevious, isPersonValid } = step2HookData
Please update this branch, because this functionality changed

2021-06-23 08:00 UTC, mariuspop86 commented on src/components/Journeys/PrivateCompany/Step2/Step2Form.tsx
> +          closeCard={() => toggleDisplayCard()}
```suggestion
          closeCard={toggleDisplayCard}
```

2021-06-23 08:02 UTC, mariuspop86 commented on src/components/Journeys/PrivateCompany/Step2/Step2View.tsx
> +        <PersonInfoSection
```suggestion
        <PersonInfoSection
            {...{toggleDelete, toggleEdit, documentsStatus, isDocumentInvalid, isEditModeOpen, person, index}}
        />
```

2021-06-24 05:56 UTC, andreir-suciu approved these changes

2021-06-24 08:26 UTC, merged