KLBP-305: Redirect to 401 page when patch breadcrumb fails.
beprems/KYB-lbp-front pull request #165
Opened 2021-06-16 08:19 UTC by andreir-suciu

2021-06-16 08:20 UTC, mariuspop86 approved these changes

2021-06-16 08:36 UTC, ioan-iacob-netea approved these changes

2021-06-16 08:41 UTC, iuliudascalu approved these changes

2021-06-16 08:43 UTC, mariuspop86 commented on src/hooks/useStep2Hook.ts
> +    try {
Please add a test

2021-06-16 16:57 UTC, mariapitechplus approved these changes

2021-06-17 05:10 UTC, andreir-suciu commented on src/hooks/useStep2Hook.ts
> +    try {
Done

2021-06-17 06:43 UTC, ioan-iacob-netea requested changes

2021-06-17 06:43 UTC, ioan-iacob-netea commented on src/interfaces/Breadcrumb.ts
> +  revisit?: boolean
Please sort the interface properties.

2021-06-17 06:49 UTC, andreir-suciu commented on src/interfaces/Breadcrumb.ts
> +  revisit?: boolean
Done.

2021-06-17 06:52 UTC, mariuspop86 approved these changes

2021-06-17 07:11 UTC, ioan-iacob-netea approved these changes

2021-06-17 07:48 UTC, merged