Feature/klbp 276 association change typology
beprems/KYB-lbp-front pull request #203
Opened 2021-06-28 16:33 UTC by mariuspop86

2021-06-28 17:46 UTC, andreir-suciu approved these changes

2021-06-28 19:25 UTC, ioan-iacob-netea requested changes

2021-06-28 19:25 UTC, ioan-iacob-netea commented on src/interfaces/Folder.ts
> +  categorie_juridique?: string
Please sort interface properties :)

2021-06-29 09:28 UTC, ioan-iacob-netea approved these changes

2021-06-30 12:35 UTC, merged