KLBP-199: Step 3 private company.
beprems/KYB-lbp-front pull request #206
Opened 2021-06-29 16:12 UTC by andreir-suciu

2021-06-29 21:59 UTC, mariapitechplus commented on src/components/Journeys/Common/SecondaryPersonViewMode.tsx
> +  const step3PersonHookData = useSecondaryPersonHook(
Please rename this variable to $secondaryPersonHook or something similar since it is use for both step 2 and 3

2021-06-29 22:00 UTC, mariapitechplus commented on src/components/Journeys/Common/SecondaryPersonViewMode.tsx
> +    documentType || '',
Could you please rename the useStep2ViewModeHook so it doesn't have the Step2 in its name because it is used for other steps too

2021-06-29 22:02 UTC, mariapitechplus commented on src/components/Journeys/Common/SecondaryPersonViewMode.tsx
> +    documentType || '',
I would prefer to keep identity_document_type instead of documentType because it leads to confusion between identity document type ( the dropdown) and the document type ( typeId on file state)

2021-06-29 22:10 UTC, mariapitechplus commented on src/components/Journeys/PrivateCompany/Step2/Step2Content.tsx
> +                  secondaryPersonHookData={step2PrivateCompanyHookData}
I know that the SecondaryPersonViewMode is used both in step 2 and 3 and the prop secondaryPersonHookData has different values based in step 3, but I would rename this prop to reflect the private hook because we have another hook called useSecondaryPersonHook and looking to this prop it makes me think that I have the data coming from this one. Maybe rename it to **privateCompanyHookData**

2021-06-30 05:41 UTC, andreir-suciu commented on src/components/Journeys/Common/SecondaryPersonViewMode.tsx
> +    documentType || '',
I would keep the variable documentType because I cannot use identity_document_type as it was used before. In useSecondaryPersonData we already have identity_document_type that is the value from person and identityDocumentType that is the value from dropdown. The variable documentType's value is (identityDocumentType.value || identity_document_type).The first value is from dropdown  identityDocumentType and only if it do not exists we should use the value from person.

2021-06-30 06:56 UTC, ioan-iacob-netea requested changes

2021-06-30 06:56 UTC, ioan-iacob-netea commented on src/enums/common.ts
> +export const MONTANT_LIMIT = 200000
Is this still used? The check on the additional upload file on the 1st step depended on this at first but then was changed to 2 other person info properties.

2021-06-30 06:56 UTC, ioan-iacob-netea commented on src/interfaces/Step.ts
> +  representativeType?: string
Please move this down 1 line in order for the interface to be sorted. :)

2021-06-30 06:56 UTC, ioan-iacob-netea commented on src/interfaces/Step3.ts
> +  invalidPersons: ISecondaryPersonData[]
Please sort interface properties.

2021-06-30 06:56 UTC, ioan-iacob-netea commented on src/interfaces/Step3.ts
> +  typeId: string
Please sort interface properties.

2021-06-30 06:56 UTC, ioan-iacob-netea commented on src/lang/fr.json
> +  "form.field.beneficialOwner.birthDate.label" : "Date de naissance *",
Please move beneficialOwner translations above "form.field.companyType" in order to maintain the translations order.

2021-06-30 06:56 UTC, ioan-iacob-netea commented on src/lang/fr.json
> +  "modal.button.close":  "Annuler",
Please move "modal" translations above "private" translations in order to maintain the their sorted order.

2021-06-30 06:56 UTC, ioan-iacob-netea commented on src/lang/fr.json
> +  "step2.form.field.beneficialOwner.identity_document_type.label" : "Veuillez sélectionner un justificatif prouvant l’identité du Bénéficiaire Effectif *",
Please move this translation above a few line in order to maintain the sorted order.

2021-06-30 06:56 UTC, ioan-iacob-netea commented on src/lang/fr.json
> +  "step2.view.beneficialOwner.firstName.label" : "Prénom du BE",
Please sort these translations.

2021-06-30 06:56 UTC, ioan-iacob-netea commented on src/lang/fr.json
> +  "step2.tooltip.text1": "La réglementation nous impose de disposer d'une connaissance approfondie et actualisée de nos clients. Nous sommes donc dans l'obligation de mettre régulièrement à jour vos
Please order these translations.

2021-06-30 09:57 UTC, iuliudascalu commented on src/components/Journeys/PrivateCompany/Step3/BeneficialOwnerUploadSection.tsx
> +      <div>
You can remove the div and the fragment.

2021-06-30 13:34 UTC, ioan-iacob-netea approved these changes

2021-06-30 13:43 UTC, mariuspop86 commented on src/hooks/useDocumentsHook.ts
> +        currentStep: step,
👍

2021-06-30 13:51 UTC, mariuspop86 approved these changes

2021-06-30 14:10 UTC, merged