WIP: KLBP-36: Styling confirmation page.
beprems/KYB-lbp-front pull request #22
Opened 2021-04-21 07:03 UTC by iuliudascalu

2021-04-21 11:10 UTC, ioan-iacob-netea requested changes

2021-04-21 11:10 UTC, ioan-iacob-netea commented on src/assets/images/index.ts
> +export { logo, spinner, confirmationIcon }
Please order alphabetically the import and export elements.

2021-04-21 11:10 UTC, ioan-iacob-netea commented on src/components/Confirmation.tsx
> +        Nous vous remercions
Please use translations for texts outside tests.

2021-04-21 13:10 UTC, iuliudascalu commented on src/components/Confirmation.tsx
> +        Nous vous remercions
Done.

2021-04-21 13:10 UTC, iuliudascalu commented on src/assets/images/index.ts
> +export { logo, spinner, confirmationIcon }
Done.

2021-04-21 14:09 UTC, ioan-iacob-netea requested changes

2021-04-21 14:09 UTC, ioan-iacob-netea commented on src/lang/fr.json
> +  "confirmation.page.description.2": "Vous pouvez désormais quitter cette page."
Please order the translations.

2021-04-21 15:24 UTC, iuliudascalu commented on src/lang/fr.json
> +  "confirmation.page.description.2": "Vous pouvez désormais quitter cette page."
Done.

2021-04-21 15:42 UTC, ioan-iacob-netea approved these changes

2021-04-22 07:03 UTC, emilomirpitechplus approved these changes

2021-04-22 07:05 UTC, andreir-suciu approved these changes

2021-04-22 08:53 UTC, mariuspop86 approved these changes

2021-04-23 07:08 UTC, merged