KLBP-250: Association journey step 2 implementation.
beprems/KYB-lbp-front pull request #234
Opened 2021-07-05 06:12 UTC by andreir-suciu

2021-07-05 07:40 UTC, ioan-iacob-netea requested changes

2021-07-05 07:40 UTC, ioan-iacob-netea commented on src/components/Journeys/Association/Step2/PersonInfoSection.tsx
> +    toggleDelete,
Please sort props.

2021-07-05 07:40 UTC, ioan-iacob-netea commented on src/interfaces/Step2.ts
> +  step2HookData: IStep2HookData
Please sort interface properties.

2021-07-05 07:40 UTC, ioan-iacob-netea commented on src/enums/journeys.ts
> +  NON_SIRENEE_ASSOCIATION: '2',
Instead of NON_SIRENEE_ASSOCIATION and SIRENEE_ASSOCIATION wouldn't the names ASSOCIATION_NON_SIRENE and ASSOCIATION_SIRENE stand out more as being similar types of companies? Both in FE and BE we use the same logic for these company types in some places. Also sirene should be with 1 E as I double-checked the tickets where it is mentioned.

2021-07-05 07:40 UTC, ioan-iacob-netea commented on src/enums/common.ts
> +  COPR: '162',
Please try to use non-abreviated names for constants.

2021-07-07 08:58 UTC, andreir-suciu commented on src/enums/journeys.ts
> +  NON_SIRENEE_ASSOCIATION: '2',
Fixed here: https://github.com/beprems/KYB-lbp-front/pull/229
This changes were added in step 1 association implementation. Please try to avoid to comment on changes that are from other MRs as it is confusing. You can check here the changes for step 2 https://github.com/beprems/KYB-lbp-front/pull/234/commits/6488130b48401387dde9ab55856843f2520b0591  . Same for the changes from common.ts file. Updated in step 1 MR (I added only comment near the const declaration where i thought it was necessary. I think we should keep BE name for constant as they are shorter and easier to use and I don't see any utility in adding the full name ).

2021-07-07 13:45 UTC, mariuspop86 requested changes

2021-07-07 13:45 UTC, mariuspop86 commented on src/components/Journeys/Association/Step1/Step1DocumentsSection.tsx
> +          <React.Fragment key={index.toString()}>
This should be it's own component

2021-07-07 13:45 UTC, mariuspop86 commented on src/components/Journeys/Association/Step2/Step2Content.tsx
> +      {isPersonValid && <WarningDisclaimerSection />}
This line can be removed and the component should be added bellow in the ternary. Please be careful when adding logic into the template

2021-07-07 13:45 UTC, mariuspop86 commented on src/components/Journeys/Association/Step2/Step2View.tsx
> +                  onClick={() => {
```suggestion
                  onClick={validateFiles}
```

2021-07-07 13:45 UTC, mariuspop86 commented on src/components/Journeys/Common/MandatoryFieldSymbol.tsx
> +      id={translationId}
Order is missing

2021-07-07 15:04 UTC, mariuspop86 commented on src/components/Journeys/Association/Step2/Step2Form.tsx
> +          {...rest}
```suggestion
          {...{...rest, control, errors, register, representativeType: representativeType || LEGAL_REPRESENTATIVE }}
```

2021-07-07 15:04 UTC, ioan-iacob-netea commented on src/enums/journeys.ts
> +  NON_SIRENEE_ASSOCIATION: '2',
Sorry, it is harder to review particular changes when multiple branches are merged and prepared to be merged further.

2021-07-07 15:05 UTC, mariuspop86 commented on src/components/Journeys/Association/Step2/WarningDisclaimerSection.tsx
> +          tag="p"
If this is a title maybe the tag should be <h1>

2021-07-07 15:15 UTC, ioan-iacob-netea commented on src/enums/journeys.ts
> +  NON_SIRENEE_ASSOCIATION: '2',
https://medium.com/ltunes/what-is-clean-code-naming-conventions-part-1-426d383eb85d
"It is a nice practice to avoid abbreviations since they can mean something else we are not aware of." and it also introduces an additional layer of ambiguity. Referring to a document, in our case, as "document_containing_this_information" or "document_for_that_purpose" helps the other developers understand its purpose rather than abbreviations that they would need to follow up within the ticket or documentation to understand. As developers we spend a lot of time debugging and it helps not needing to juggle between sources of information of the lack thereof.
I would recommend that you read the book Clean Code as it is very well documented based on the author's years of experience.

2021-07-08 07:01 UTC, iuliudascalu commented on src/components/Journeys/Association/Step2/WarningDisclaimerSection.tsx
> +          tag="p"
It is the title of the banner not the title of the page so this should not be an h1, it can be an h3 tho.

2021-07-08 07:22 UTC, iuliudascalu approved these changes

2021-07-08 07:29 UTC, mariuspop86 commented on src/components/Journeys/Association/Step2/WarningDisclaimerSection.tsx
> +          tag="p"
I set the h1 as an example, what I wanted to say that should be a heading tag

2021-07-08 07:40 UTC, andreir-suciu commented on src/components/Journeys/Association/Step2/WarningDisclaimerSection.tsx
> +          tag="p"
tag changed to h3

2021-07-08 08:36 UTC, ioan-iacob-netea approved these changes

2021-07-08 08:36 UTC, merged