KLBP-397: Delete persons if no is selected, KLBP-399: Disable button conditions update.
beprems/KYB-lbp-front pull request #248
Opened 2021-07-06 13:52 UTC by andreir-suciu

2021-07-06 15:24 UTC, mariapitechplus commented on src/components/Journeys/PrivateCompany/Step3/Step3Content.tsx
> +        isNextDisabled={isBeneficialOwner === NO_VALUE ? false : isNextDisabled}
can we determine this in the hook that returns isNextDisabled please? I would avoid having logic that determine if this button is disabled or not in two places.

2021-07-06 18:41 UTC, ioan-iacob-netea requested changes

2021-07-06 18:41 UTC, ioan-iacob-netea commented on src/components/Journeys/PrivateCompany/Step3/BeneficialOwnerQuestion.tsx
> +        key={isBeneficialOwner}
Please keep the properties sorted.

2021-07-07 06:48 UTC, ioan-iacob-netea approved these changes

2021-07-07 06:52 UTC, mariuspop86 approved these changes

2021-07-07 06:53 UTC, merged