KLBP-28: Step 2 page setup.
beprems/KYB-lbp-front pull request #28
Opened 2021-04-23 07:07 UTC by andreir-suciu

2021-04-23 07:10 UTC, iuliudascalu commented on package.json
> +    "kyb-core": "git+ssh://git@github.com/beprems/KYB-core.git#v1.3.3",
The last version is 1.3.4 :D

2021-04-23 07:12 UTC, iuliudascalu commented on src/components/FormGroup/MySelect.tsx
> +  const intl = useIntl()
If we are using react-select, i think that we no longer need this componenet.

2021-04-23 07:14 UTC, iuliudascalu commented on src/components/LegalRepresentativeCard/LegalRepresentativeCard.tsx
> +export interface ILegalRepresentativeCard {
Please move this interface in a new file.

2021-04-23 07:29 UTC, andreir-suciu commented on package.json
> +    "kyb-core": "git+ssh://git@github.com/beprems/KYB-core.git#v1.3.3",
Updated core version. Thx :D

2021-04-23 07:29 UTC, andreir-suciu commented on src/components/FormGroup/MySelect.tsx
> +  const intl = useIntl()
Removed MySelect.

2021-04-23 07:30 UTC, andreir-suciu commented on src/components/LegalRepresentativeCard/LegalRepresentativeCard.tsx
> +export interface ILegalRepresentativeCard {
Done.

2021-04-23 07:44 UTC, ioan-iacob-netea approved these changes

2021-04-23 08:53 UTC, iuliudascalu approved these changes

2021-04-26 06:29 UTC, mariuspop86 commented on src/lang/fr.json
> +  "form.select.option.idCard": "Piece d'identite",
If this are fields in step 2 please use this format "step2.form.select..."

2021-04-26 06:30 UTC, mariuspop86 commented on src/pages/steps/Step2.tsx
> +        <Title
```suggestion
        <Title
         title={intl.formatMessage({
            id: 'step2.title',
          })}
        />
```

2021-04-26 08:01 UTC, ioan-iacob-netea requested changes

2021-04-26 08:01 UTC, ioan-iacob-netea commented on src/components/FormGroup/SelectInput.tsx
> +  placeholder = 'chooseOption',
Please add the placeholder as a translated/translatable string.

2021-04-26 10:38 UTC, andreir-suciu commented on src/components/FormGroup/SelectInput.tsx
> +          id={`form.field.legalRepresentative.${id}.label`}
Done. I added a new param "page" where you can send the content that will be concatenated in place of legalRepresentative.

2021-04-26 10:38 UTC, andreir-suciu commented on src/lang/fr.json
> +  "form.select.option.idCard": "Piece d'identite",
Done.

2021-04-26 10:39 UTC, andreir-suciu commented on src/pages/steps/Step2.tsx
> +        <Title
Done. I also added a ts-ignore as it requires the "children" prop. I will update the Title component in core with next MR and remove the ts-ignore.

2021-04-26 18:48 UTC, mariuspop86 approved these changes

2021-04-26 18:48 UTC, mariuspop86 commented on src/pages/steps/Step2.tsx
> +        <Title
Hmm, maybe we should check the core component if the children props is really necessary, and maybe make it optional

2021-04-26 18:48 UTC, mariuspop86 commented on src/components/step2/Step2Form.tsx
> +      {isLegalRepresentative && (
Instead of having all of this conditional rendering we should have separate components for this. It's really hard to read this way

2021-04-27 08:08 UTC, ioan-iacob-netea approved these changes

2021-04-27 11:49 UTC, andreir-suciu commented on src/components/step2/Step2Form.tsx
> +      {isLegalRepresentative && (
Done. Created LegalRepresentative section and SelectUploadDocument a component that contains select option and upload document.

2021-04-28 11:04 UTC, merged