KLBP-433: Fixed user cannot proceed to next step due to a missing file.
beprems/KYB-lbp-front pull request #309
Opened 2021-07-16 11:25 UTC by iuliudascalu

2021-07-19 07:52 UTC, ioan-iacob-netea requested changes

2021-07-19 07:52 UTC, ioan-iacob-netea commented on src/hooks/useAssociationStep1FormHook.ts
> +  if (isAutocertifOrEnfPassive && initialState.length === 6) {
Please create constants for all the values used (4, 5, 6, 7, 8).

2021-07-19 08:24 UTC, iuliudascalu commented on src/hooks/useAssociationStep1FormHook.ts
> +  if (isAutocertifOrEnfPassive && initialState.length === 6) {
Can you plese suggest what name should have ?

2021-07-19 08:28 UTC, mariuspop86 commented on src/hooks/useAssociationStep1FormHook.ts
> +  if (isAutocertifOrEnfPassive && initialState.length === 6) {
File_status?

2021-07-19 13:28 UTC, iuliudascalu commented on src/hooks/useAssociationStep1FormHook.ts
> +  if (isAutocertifOrEnfPassive && initialState.length === 6) {
Done.

2021-07-19 13:32 UTC, ioan-iacob-netea approved these changes

2021-07-19 13:36 UTC, mariuspop86 commented on src/components/Journeys/Association/Step1/Step1DocumentsSection.tsx
>        <StepNavButtons
```suggestion
      <StepNavButtons
     {... {isNextDisabled, onClickNext, displayPrevious: false...}}
     
```

2021-07-19 13:39 UTC, mariuspop86 commented on src/services/API/document.ts
> +export async function deleteDocument(typeId: string, personTypeId: string) {
Please update the function at line 165
```
export async function deleteSecondaryPersonDocuments() {
  return await deleteDocument('1', RL_PERSON_TYPE_ID)
} 
```

2021-07-20 06:01 UTC, andreibuhus approved these changes

2021-07-20 08:56 UTC, iuliudascalu commented on src/components/Journeys/Association/Step1/Step1DocumentsSection.tsx
>        <StepNavButtons
Done.

2021-07-20 08:57 UTC, iuliudascalu commented on src/services/API/document.ts
> +export async function deleteDocument(typeId: string, personTypeId: string) {
Done.

2021-07-20 11:01 UTC, mariuspop86 commented on src/services/API/document.ts
> +  return deleteDocument('1', RL_PERSON_TYPE_ID)
'1' please use a constant

2021-07-20 11:31 UTC, iuliudascalu commented on src/services/API/document.ts
> +  return deleteDocument('1', RL_PERSON_TYPE_ID)
Done.

2021-07-20 13:20 UTC, mariuspop86 approved these changes

2021-07-20 13:34 UTC, merged