KLBP-436: Add red banner display rule based on source.
beprems/KYB-lbp-front pull request #322
Opened 2021-07-26 05:56 UTC by andreir-suciu

2021-07-26 06:13 UTC, ioan-iacob-netea requested changes

2021-07-26 06:13 UTC, ioan-iacob-netea commented on src/components/Journeys/PrivateCompany/Step2/Step2Content.tsx
> +    areValidPersonsFromImport,
Please move the constant down one line to keep the alphabetical order.

2021-07-26 06:13 UTC, ioan-iacob-netea commented on src/hooks/useStep2PrivateCompanyHook.ts
> +    areValidPersonsFromImport,
Same as above.

2021-07-26 06:33 UTC, mariuspop86 approved these changes

2021-07-27 06:36 UTC, ioan-iacob-netea approved these changes

2021-07-27 08:07 UTC, iuliudascalu approved these changes

2021-07-28 05:54 UTC, merged