KLBP-438: Increase coverage tests hooks.
beprems/KYB-lbp-front pull request #331
Opened 2021-08-05 10:19 UTC by andreir-suciu

2021-08-06 09:53 UTC, ioan-iacob-netea requested changes

2021-08-06 09:53 UTC, ioan-iacob-netea commented on src/__tests__/pages/ConfirmationPage/ConfirmationPage.test.tsx
> +  test('User is redirected to login page if the token is expired', async () => {
As discussed, the describe/test is meant as a complete sentence therefore it is redundant to repeat parts of the texts. Please try to continue within the "test" statement the sentence started with the "describe".
Ex:
 ```
describe('Based on token validation and journey status' () => {
        test('the user is redirected to the login page if the token is expired', () =>{})
        test('the user is redirected to the confirmation page if the journey is complete', () => {})
      })
```

2021-08-13 07:15 UTC, mariuspop86 approved these changes

2021-08-18 07:10 UTC, ioan-iacob-netea approved these changes

2021-08-18 07:12 UTC, merged