KYB-38: Homepage with token check and redirect.
beprems/KYB-lbp-front pull request #4
Opened 2021-04-07 12:22 UTC by andreir-suciu

2021-04-07 15:13 UTC, mariuspop86 commented on src/hooks/useCheckTokenHook.ts
> +  const [authorized, setAuthorized] = useState<boolean>(!token)
This variable name is misleading. You are using this variable to show a loader until the request if finished. Maybe rename this to status or loading? I would go tor `status` and change the value to a constant.

2021-04-08 07:28 UTC, emilomirpitechplus commented on src/components/Homepage/HomepageContent.tsx
> +          <DynamicFormattedMessage
I think we should use the button component from the core library

2021-04-08 09:25 UTC, ioan-iacob-netea requested changes

2021-04-08 09:25 UTC, ioan-iacob-netea commented on src/lang/fr.json
> +  "homepage.button.continue" : "Continuer"
Please order the labels alphabetically. This will make future amendments easier to identify and update.

2021-04-08 09:56 UTC, iuliudascalu commented on src/lang/fr.json
> +  "homepage.button.continue" : "Continuer"
Also you can make nesting so this will be someting like this: 

"home": {
 "text": {
  "3":"soyez....",
  "4":"(1)..."
 }
 "button":{
  "continue": "continuer.."
 }
}

2021-04-08 10:37 UTC, andreir-suciu commented on src/hooks/useCheckTokenHook.ts
> +  const [authorized, setAuthorized] = useState<boolean>(!token)
Done.

2021-04-08 10:37 UTC, andreir-suciu commented on src/components/Homepage/HomepageContent.tsx
> +          <DynamicFormattedMessage
Done.

2021-04-08 10:43 UTC, andreir-suciu commented on src/lang/fr.json
> +  "homepage.button.continue" : "Continuer"
@ioan-iacob-netea Done. @iuliudascalu react-intl does not support nested messages.

2021-04-08 11:39 UTC, ioan-iacob-netea approved these changes

2021-04-08 11:40 UTC, emilomirpitechplus approved these changes

2021-04-08 13:10 UTC, iuliudascalu approved these changes

2021-04-09 09:07 UTC, mariuspop86 approved these changes

2021-04-12 12:05 UTC, merged