KLBP-40: Login user and redirect to journey.
beprems/KYB-lbp-front pull request #6
Opened 2021-04-12 12:13 UTC by andreir-suciu

2021-04-12 12:41 UTC, ioan-iacob-netea requested changes

2021-04-12 12:41 UTC, ioan-iacob-netea commented on src/components/PageSpinner.tsx
> +import React, { ReactElement } from 'react'
Please add the spinner as a component in KYB-core.

2021-04-12 12:41 UTC, ioan-iacob-netea commented on src/pages/Home.tsx
> +        return <Redirect to={ROUTES.step1} />
Please amend the route to step2.

2021-04-13 06:12 UTC, iuliudascalu approved these changes

2021-04-13 06:17 UTC, emilomirpitechplus approved these changes

2021-04-15 05:06 UTC, andreir-suciu commented on src/components/PageSpinner.tsx
> +import React, { ReactElement } from 'react'
Done.

2021-04-15 05:07 UTC, andreir-suciu commented on src/pages/Home.tsx
> +        return <Redirect to={ROUTES.step1} />
Done.

2021-04-15 08:43 UTC, mariuspop86 commented on src/components/PageSpinner.tsx
> +import React, { ReactElement } from 'react'
But do we need this page if we have the Spinner component into the core?

2021-04-15 08:45 UTC, mariuspop86 commented on src/enums/routes.ts
> +  step1: '/parcours/step1',
I would change this to it's corespondent in the breadcrumb
`step1` -> company
`step2` -> legalRepresentative

2021-04-15 08:46 UTC, mariuspop86 commented on src/lang/fr.json
> +  "homepage.text3": "Soyez rassuré, vos données resteront protégées et confidentielles, conformément à la <a>Politique de Protection des Données Personnelles de La Banque Postale.</a>",
An anchor tag should have a `href` attribute

2021-04-15 08:48 UTC, andreir-suciu commented on src/components/PageSpinner.tsx
> +import React, { ReactElement } from 'react'
We need it because this is the component that render the spinner from core based on store state and it is placed at the same level with Routes component from App.

2021-04-15 08:51 UTC, andreir-suciu commented on src/lang/fr.json
> +  "homepage.text3": "Soyez rassuré, vos données resteront protégées et confidentielles, conformément à la <a>Politique de Protection des Données Personnelles de La Banque Postale.</a>",
The href, classes and any other props are added in values prop from DynamicFormattedMessage where it is defined tag funtionality. For this anchor it is added in HomepageComponent.

2021-04-15 09:01 UTC, mariuspop86 commented on src/__tests__/store/slices/Loading.test.ts
> +})
You should add tests for initialDataReceived and initialDataFailed actions too

2021-04-15 09:32 UTC, mariuspop86 requested changes
The translations must be reviewed. We should not have html tags into the them

2021-04-15 12:53 UTC, andreir-suciu commented on src/__tests__/store/slices/Loading.test.ts
> +})
Done.

2021-04-16 08:32 UTC, ioan-iacob-netea approved these changes

2021-04-16 08:44 UTC, mariuspop86 approved these changes

2021-04-16 08:55 UTC, merged