KLBP-29: Step 2 create new person.
beprems/KYB-lbp-front pull request #62
Opened 2021-05-13 16:31 UTC by andreir-suciu

2021-05-13 18:13 UTC, ioan-iacob-netea requested changes

2021-05-13 18:13 UTC, ioan-iacob-netea commented on src/interfaces/Folder.ts
> +  is_kyb_legal_representative: string
Please use camelCase for this property name.

2021-05-13 18:13 UTC, ioan-iacob-netea commented on src/enums/journeys.ts
> +export const STEP_1_ID = '0'
:+1:

2021-05-13 18:13 UTC, ioan-iacob-netea commented on src/components/step2/Step2Form.tsx
> +  validateFiles: () => undefined | true
```suggestion
  validateFiles: () => undefined | bool
```

2021-05-14 05:46 UTC, andreir-suciu commented on src/__mock__/folderMock.ts
> +  is_kyb_legal_representative: '1',
Done

2021-05-14 05:46 UTC, andreir-suciu commented on src/__tests__/pages/steps/Step2.test.tsx
> +    expect(screen.queryByText('Nom du RL*')).not.toBeInTheDocument()
Updated.

2021-05-14 05:46 UTC, andreir-suciu commented on src/interfaces/Folder.ts
> +  is_kyb_legal_representative: string
Done

2021-05-14 05:47 UTC, andreir-suciu commented on src/components/step2/Step2Form.tsx
> +  validateFiles: () => undefined | true
reviewed all interface properties at is was automatically generated and updated where necessary

2021-05-14 08:15 UTC, ioan-iacob-netea approved these changes

2021-05-14 09:41 UTC, iuliudascalu approved these changes

2021-05-14 11:20 UTC, ioan-iacob-netea approved these changes

2021-05-17 11:58 UTC, mariuspop86 commented on src/components/StepNavButtons/StepNavButtons.tsx
> +  nextButtonType = 'submit',
I don't think this change is really necessar

2021-05-17 12:00 UTC, mariuspop86 commented on src/components/step2/Step2Form.tsx
> +export interface IStep2HookData {
Please move this to the interfaces folder

2021-05-17 12:01 UTC, mariuspop86 commented on src/components/step2/Step2Form.tsx
> +const YES_VALUE = '1'
Please move this in the enums folder

2021-05-17 12:02 UTC, mariuspop86 commented on src/hooks/useStep1FormHook.ts
> +    personTypeId: '101', // TODO update when we have the correct type
Please revert this. This was fixed here https://github.com/beprems/KYB-lbp-front/pull/60

2021-05-17 12:24 UTC, mariuspop86 commented on src/interfaces/FormFields.ts
> +  rules?: any
```suggestion
  rules?: Record<string, object>
```

2021-05-17 12:46 UTC, mariuspop86 approved these changes

2021-05-17 12:46 UTC, mariuspop86 commented on src/interfaces/LegalRepresentative.ts
> +  rules?: any
Here also.

2021-05-17 12:46 UTC, mariuspop86 commented on src/hooks/useStep2Hook.ts
> +
```suggestion
onSubmit(formData)
```

2021-05-18 10:36 UTC, andreir-suciu commented on src/components/StepNavButtons/StepNavButtons.tsx
> +  nextButtonType = 'submit',
Removed nextButtonType.

2021-05-18 10:37 UTC, andreir-suciu commented on src/components/step2/Step2Form.tsx
> +export interface IStep2HookData {
Moved to Step2.ts

2021-05-18 10:37 UTC, andreir-suciu commented on src/components/step2/Step2Form.tsx
> +const YES_VALUE = '1'
Moved to enum folders.

2021-05-18 10:37 UTC, andreir-suciu commented on src/hooks/useStep1FormHook.ts
> +    personTypeId: '101', // TODO update when we have the correct type
Done

2021-05-18 10:37 UTC, andreir-suciu commented on src/interfaces/FormFields.ts
> +  rules?: any
Fixed.

2021-05-18 10:37 UTC, andreir-suciu commented on src/interfaces/LegalRepresentative.ts
> +  rules?: any
Fixed.

2021-05-18 10:37 UTC, andreir-suciu commented on src/hooks/useStep2Hook.ts
> +
Fixed.

2021-05-18 10:43 UTC, mariuspop86 commented on src/hooks/useStep2Hook.ts
> +      if (isUnauthorized(error)) {
This is not needed, it's already done in `handleError`

2021-05-18 10:53 UTC, andreir-suciu commented on src/hooks/useStep2Hook.ts
> +      if (isUnauthorized(error)) {
Removed.

2021-05-18 10:54 UTC, merged